import BrazilHeaderImageURL from '../assets/images/Brazil.jpg';
import IndonesiaHeaderImageURL from '../assets/images/Indonesia.jpg';
import MexicoHeaderImageURL from '../assets/images/Mexico.jpg';
import PeruHeaderImageURL from '../assets/images/Peru.jpg';
import IvoryCoastHeaderImageURL from '../assets/images/IvoryCoast.jpg';
import ColombiaHeaderImageURL from '../assets/images/Colombia.jpg';
import EcuadorHeaderImageURL from '../assets/images/Ecuador.jpg';
import NigeriaHeaderImageURL from '../assets/images/Nigeria.jpg';

import IndonesiaFlagURL from '../assets/flags/Indonesia.png';
import EastKalimantanFlagURL from '../assets/flags/East_Kalimantan.png';
import WestKalimantanFlagURL from '../assets/flags/West_Kalimantan.png';

export default [
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: null,
    URL: '/brazil',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: null,
    URL: '/indonesia',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: null,
    URL: '/mexico',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: null,
    URL: '/peru',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Ivory Coast',
    HEADER_IMAGE_URL: IvoryCoastHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'CoteDivoire',
    JURISDICTION_NAME: null,
    URL: '/cotedivoire',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Colombia',
    HEADER_IMAGE_URL: ColombiaHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Colombia',
    JURISDICTION_NAME: null,
    URL: '/colombia',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Ecuador',
    HEADER_IMAGE_URL: EcuadorHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Ecuador',
    JURISDICTION_NAME: null,
    URL: '/ecuador',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Nigeria',
    HEADER_IMAGE_URL: NigeriaHeaderImageURL,
    JURISDICTION_TYPE: 'nation',
    NATION_NAME: 'Nigeria',
    JURISDICTION_NAME: null,
    URL: '/nigeria',
  },
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Acre, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Acre',
    URL: '/brazil/acre',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Aceh, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'Aceh',
    URL: '/indonesia/aceh',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Campeche, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Campeche',
    URL: '/mexico/campeche',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Amazonas, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'Amazonas',
    URL: '/peru/amazonas',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Bélier, Ivory Coast',
    HEADER_IMAGE_URL: IvoryCoastHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'CoteDivoire',
    JURISDICTION_NAME: 'Bélier',
    URL: '/cotedivoire/belier',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Caquetá, Colombia',
    HEADER_IMAGE_URL: ColombiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Colombia',
    JURISDICTION_NAME: 'Caquetá',
    URL: '/colombia/caqueta',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Pastaza, Ecuador',
    HEADER_IMAGE_URL: EcuadorHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Ecuador',
    JURISDICTION_NAME: 'Pastaza',
    URL: '/ecuador/pastaza',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Cross River, Nigeria',
    HEADER_IMAGE_URL: NigeriaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Nigeria',
    JURISDICTION_NAME: 'Cross River',
    URL: '/nigeria/crossriver',
  },
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Amapá, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Amapá',
    URL: '/brazil/amapa',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Central Kalimantan, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'C. Kalimantan',
    URL: '/indonesia/centralkalimantan',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Chiapas, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Chiapas',
    URL: '/mexico/chiapas',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Huánuco, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'Huánuco',
    URL: '/peru/huanuco',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Cavally, Ivory Coast',
    HEADER_IMAGE_URL: IvoryCoastHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'CoteDivoire',
    JURISDICTION_NAME: 'Cavally',
    URL: '/cotedivoire/cavally',
  },
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Amazonas, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Amazonas',
    URL: '/brazil/amazonas',
  },
  {
    FLAGS: [IndonesiaFlagURL, EastKalimantanFlagURL],
    FULL_NAME: 'East Kalimantan, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'E. Kalimantan',
    URL: '/indonesia/eastkalimantan',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Jalisco, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Jalisco',
    URL: '/mexico/jalisco',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Loreto, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'Loreto',
    URL: '/peru/loreto',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Maranhão, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Maranhão',
    URL: '/brazil/maranhao',
  },
  {
    FLAGS: [],
    FULL_NAME: 'North Kalimantan, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'N. Kalimantan',
    URL: '/indonesia/northkalimantan',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Oaxaca, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Oaxaca',
    URL: '/mexico/oaxaca',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Madre de Dios, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'Madre de Dios',
    URL: '/peru/madrededios',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Mato Grosso, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Mato Grosso',
    URL: '/brazil/matogrosso',
  },
  {
    FLAGS: [IndonesiaFlagURL, WestKalimantanFlagURL],
    FULL_NAME: 'West Kalimantan, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'W. Kalimantan',
    URL: '/indonesia/westkalimantan',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Quintana Roo, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Quintana Roo',
    URL: '/mexico/quintanaroo',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Piura, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'Piura',
    URL: '/peru/piura',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Pará, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Pará',
    URL: '/brazil/para',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Papua, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'Papua',
    URL: '/indonesia/papua',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Tabasco, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Tabasco',
    URL: '/mexico/tabasco',
  },
  {
    FLAGS: [],
    FULL_NAME: 'San Martín, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'San Martín',
    URL: '/peru/sanmartin',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Rondônia, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Rondônia',
    URL: '/brazil/rondonia',
  },
  {
    FLAGS: [],
    FULL_NAME: 'West Papua, Indonesia',
    HEADER_IMAGE_URL: IndonesiaHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Indonesia',
    JURISDICTION_NAME: 'West Papua',
    URL: '/indonesia/westpapua',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Yucatán, Mexico',
    HEADER_IMAGE_URL: MexicoHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Mexico',
    JURISDICTION_NAME: 'Yucatán',
    URL: '/mexico/yucatan',
  },
  {
    FLAGS: [],
    FULL_NAME: 'Ucayali, Peru',
    HEADER_IMAGE_URL: PeruHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Peru',
    JURISDICTION_NAME: 'Ucayali',
    URL: '/peru/ucayali',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Roraima, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Roraima',
    URL: '/brazil/roraima',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  {
    FLAGS: [],
    FULL_NAME: 'Tocantins, Brazil',
    HEADER_IMAGE_URL: BrazilHeaderImageURL,
    JURISDICTION_TYPE: 'state',
    NATION_NAME: 'Brazil',
    JURISDICTION_NAME: 'Tocantins',
    URL: '/brazil/tocantins',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
];
